'use client';
export const dynamic = 'force-static';
import { useEffect, useRef, useState } from 'react';
import type { User } from '@supabase/supabase-js';
import { ArrowLeft, ArrowRight, BookOpen, Check, Clock3, Gamepad2, Lightbulb, RotateCcw, Settings, Sparkles, Trophy, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { supabase } from '@/lib/supabase';
import { AUXILIARY_FORMS, FALLBACK_GAME_ITEMS, FALLBACK_VERBS, PRONOUNS, normalizeAnswer, splitStemChange, splitVerbForm, type GameItem, type VerbGameItem } from '@/lib/game-content';

const APP_VERSION = '0.7.3';
type GameKey = 'opposites' | 'verb_past';
type VerbMode = 'preterite' | 'perfect';
function shuffle<T>(values: T[]) { const result = [...values]; for (let i = result.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [result[i], result[j]] = [result[j], result[i]]; } if (result.length > 1 && result[0] === values[0]) result.push(result.shift()!); return result; }
function HighlightedWord({ word, ending, comparisonWord, comparisonEnding = '' }: { word: string; ending: string; comparisonWord?: string; comparisonEnding?: string }) { const parts = splitVerbForm(word, ending); const comparison = comparisonWord ? splitVerbForm(comparisonWord, comparisonEnding) : null; const stem = comparison ? splitStemChange(parts.stem, comparison.stem) : { prefix: parts.stem, change: '', suffix: '' }; return <span className="font-semibold">{stem.prefix}<span className="text-red-600">{stem.change}</span>{stem.suffix}<span className="text-red-600">{parts.ending}</span>{parts.remainder}</span>; }

export default function PracticePage() {
  const [opposites, setOpposites] = useState<GameItem[]>(FALLBACK_GAME_ITEMS);
  const [verbs, setVerbs] = useState<VerbGameItem[]>(FALLBACK_VERBS);
  const [verbSequence, setVerbSequence] = useState<VerbGameItem[]>(FALLBACK_VERBS);
  const [game, setGame] = useState<GameKey | null>(null);
  const [verbMode, setVerbMode] = useState<VerbMode>('preterite');
  const [index, setIndex] = useState(0); const [answer, setAnswer] = useState(''); const [result, setResult] = useState<'correct' | 'wrong' | null>(null); const [correct, setCorrect] = useState(0); const [answered, setAnswered] = useState(0);
  const [user, setUser] = useState<User | null>(null); const [practicedSeconds, setPracticedSeconds] = useState(0); const lastTickRef = useRef<number | null>(null); const savingRef = useRef(false);
  const opposite = opposites[index % opposites.length]; const verb = verbSequence[index % verbSequence.length]; const pronounIndex = index % PRONOUNS.length;
  const expectedVerb = verbMode === 'preterite' ? verb.preterite_forms[pronounIndex] : `${AUXILIARY_FORMS[verb.perfect_auxiliary][pronounIndex]} ${verb.participle}`;
  const totalQuestions = game === 'verb_past' ? Math.max(6, verbs.length * 6) : opposites.length;
  useEffect(() => { void Promise.all([supabase.from('game_content').select('*').eq('level', 'B1').eq('game_key', 'opposites').eq('active', true).order('sort_order'), supabase.from('verb_game_content').select('*').eq('level', 'B1').eq('active', true).order('sort_order')]).then(([a, b]) => { if (a.data?.length) setOpposites(a.data as GameItem[]); if (b.data?.length) { setVerbs(b.data as VerbGameItem[]); setVerbSequence(b.data as VerbGameItem[]); } }); }, []);
  useEffect(() => { void supabase.auth.getUser().then(({ data }) => { setUser(data.user); if (data.user) void loadTodayTotal(data.user.id); }); const { data } = supabase.auth.onAuthStateChange((_e, session) => { setUser(session?.user ?? null); if (session?.user) setTimeout(() => void loadTodayTotal(session.user.id), 0); }); return () => data.subscription.unsubscribe(); }, []);
  useEffect(() => { if (!game || !user) { lastTickRef.current = null; return; } lastTickRef.current = Date.now(); const timer = window.setInterval(() => void flushPracticeTime(), 10000); const visibility = () => { if (document.hidden) void flushPracticeTime().then(() => { lastTickRef.current = null; }); else lastTickRef.current = Date.now(); }; document.addEventListener('visibilitychange', visibility); return () => { window.clearInterval(timer); document.removeEventListener('visibilitychange', visibility); void flushPracticeTime(); }; }, [game, user]);
  async function loadTodayTotal(userId: string) { const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'Europe/Vienna', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date()); const { data } = await supabase.from('practice_daily_totals').select('total_seconds').eq('user_id', userId).eq('practice_date', today).maybeSingle(); setPracticedSeconds(data?.total_seconds ?? 0); }
  async function flushPracticeTime() { if (!user || !lastTickRef.current || savingRef.current) return; const seconds = Math.floor((Date.now() - lastTickRef.current) / 1000); if (seconds < 1) return; savingRef.current = true; lastTickRef.current += seconds * 1000; const { data, error } = await supabase.rpc('record_practice_time', { seconds_played: seconds }); if (!error && typeof data === 'number') setPracticedSeconds(data); savingRef.current = false; }
  function resetRound() { setIndex(0); setAnswer(''); setResult(null); setCorrect(0); setAnswered(0); }
  function startOpposites() { setOpposites((v) => shuffle(v)); setGame('opposites'); resetRound(); }
  function startVerbs(mode: VerbMode) { setVerbSequence(shuffle(Array.from({ length: Math.max(6, verbs.length * 6) }, (_, i) => verbs[i % verbs.length]))); setVerbMode(mode); setGame('verb_past'); resetRound(); }
  function expected() { return game === 'opposites' ? opposite.opposite_word : expectedVerb; }
  function checkAnswer() { if (!answer.trim() || result) return; const cleaned = normalizeAnswer(answer).replace(/^(ich|du|er|sie|es|wir|ihr)\s+/, ''); const ok = cleaned === normalizeAnswer(expected()); setResult(ok ? 'correct' : 'wrong'); setAnswered((v) => v + 1); if (ok) setCorrect((v) => v + 1); }
  function next() { setIndex((v) => (v + 1) % totalQuestions); setAnswer(''); setResult(null); }
  async function stop() { await flushPracticeTime(); setGame(null); }
  return <main className="min-h-screen bg-[#f5f7f2] text-[#17221b]">
    <header className="border-b border-[#dce3d9] bg-white/90 px-5 py-3 md:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between"><a href="./" className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#1f6f4a] text-white"><BookOpen size={19} /></span><span><span className="block font-semibold">Lernzeit</span><span className="block text-[11px] text-[#718077]">German, one day at a time</span></span></a><nav className="flex items-center gap-1 rounded-xl bg-[#edf3ec] p-1"><a href="./" className="hidden rounded-lg px-4 py-2 text-sm text-[#718077] sm:block">Learning plan</a><span className="flex items-center gap-2 rounded-lg bg-white px-4 py-2 text-sm font-medium shadow-sm"><Sparkles size={16} />Practice</span></nav><a href="./admin.html" aria-label="Administration" className="grid size-9 place-items-center rounded-lg text-[#718077]"><Settings size={18} /></a></div></header>
    {!game ? <Catalog opposites={opposites.length} verbs={verbs.length} startOpposites={startOpposites} startVerbs={startVerbs} /> : <section className="mx-auto max-w-3xl px-5 py-8 md:px-8"><div className="mb-5 flex items-center justify-between"><Button variant="ghost" onClick={() => void stop()}><ArrowLeft />All games</Button><div className="flex items-center gap-4 text-sm font-medium text-[#637067]"><span className="flex items-center gap-2"><Clock3 size={17} />{user ? `${Math.floor(practicedSeconds / 60)} min today` : 'Sign in to record time'}</span><span className="flex items-center gap-2"><Trophy size={17} className="text-[#d09a3a]" />{correct} correct</span></div></div><div className="mb-6 h-2 overflow-hidden rounded-full bg-[#e3e8e2]"><div className="h-full rounded-full bg-[#3b8c61]" style={{ width: `${((index + (result ? 1 : 0)) / totalQuestions) * 100}%` }} /></div><article className="rounded-3xl border border-[#dce3d9] bg-white p-6 shadow-[0_14px_45px_rgba(38,65,48,0.08)] sm:p-9"><div className="flex items-center justify-between"><span className="rounded-full bg-[#edf5ef] px-3 py-1 text-xs font-semibold text-[#28734c]">B1 · {game === 'opposites' ? 'Opposites' : verbMode === 'preterite' ? 'Präteritum' : 'Perfekt'}</span><span className="text-xs text-[#87928a]">{index + 1} / {totalQuestions}</span></div>
      {game === 'opposites' ? <><p className="mt-10 text-sm font-medium text-[#718077]">What is the opposite of the highlighted word?</p><p className="mt-3 text-3xl font-medium">{opposite.phrase_before}<span className="rounded-lg bg-[#e4f2e8] px-2 py-1 text-[#1f6f4a]">{opposite.target_word}</span>{opposite.phrase_after}</p></> : <><p className="mt-10 text-sm font-medium text-[#718077]">Write this form in the <strong>{verbMode === 'preterite' ? 'Präteritum' : 'Perfekt'}</strong>.</p><p key={`${verb.id}-${pronounIndex}-${verbMode}`} className="mt-3 text-3xl font-medium"><span className="mr-2 text-[#59665e]">{PRONOUNS[pronounIndex]}</span><HighlightedWord word={verb.present_forms[pronounIndex]} ending={verb.present_endings[pronounIndex]} comparisonWord={verbMode === 'preterite' ? verb.preterite_forms[pronounIndex] : undefined} comparisonEnding={verb.preterite_endings[pronounIndex]} /></p>{verbMode === 'perfect' && <p className="mt-4 text-sm text-[#718077]">Perfekt auxiliary: <span className={`rounded-full px-3 py-1 font-semibold ${verb.perfect_auxiliary === 'sein' ? 'bg-[#dfeafb] text-[#315c9a]' : 'bg-[#f9e8c5] text-[#80581b]'}`}>{verb.perfect_auxiliary}</span></p>}</>}
      <div className="mt-9"><label className="text-sm font-medium" htmlFor="answer">Your answer</label><div className="mt-2 flex gap-2"><Input id="answer" autoFocus value={answer} disabled={!!result} onChange={(e) => setAnswer(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') result ? next() : checkAnswer(); }} placeholder={game === 'verb_past' && verbMode === 'perfect' ? 'e.g. bin gefahren' : 'Type your answer…'} className="h-12 rounded-xl text-base" /><Button onClick={result ? next : checkAnswer} disabled={!answer.trim() && !result} className="h-12 rounded-xl bg-[#1f6f4a] px-5 hover:bg-[#185c3d]">{result ? <>Next <ArrowRight /></> : <>Check <Check /></>}</Button></div></div>
      {result && <Feedback correct={result === 'correct'}>{game === 'verb_past' ? <><span className="mr-1">{PRONOUNS[pronounIndex]}</span>{verbMode === 'preterite' ? <HighlightedWord word={verb.preterite_forms[pronounIndex]} ending={verb.preterite_endings[pronounIndex]} comparisonWord={verb.present_forms[pronounIndex]} comparisonEnding={verb.present_endings[pronounIndex]} /> : <><span className={`rounded px-1 font-semibold ${verb.perfect_auxiliary === 'sein' ? 'bg-[#dfeafb] text-[#315c9a]' : 'bg-[#f9e8c5] text-[#80581b]'}`}>{AUXILIARY_FORMS[verb.perfect_auxiliary][pronounIndex]}</span> <HighlightedWord word={verb.participle} ending={verb.participle_ending} /></>}</> : <strong>{opposite.opposite_word}</strong>}</Feedback>}
      {!result && game === 'opposites' && opposite.hint && <p className="mt-5 flex items-center gap-2 text-xs text-[#7a856d]"><Lightbulb size={15} />Hint: {opposite.hint}</p>}</article>{answered >= totalQuestions && <Button variant="outline" className="mx-auto mt-5 flex" onClick={() => game === 'opposites' ? startOpposites() : startVerbs(verbMode)}><RotateCcw />Start again</Button>}</section>}
    <footer className="mx-auto flex max-w-6xl justify-end px-5 pb-6 text-[11px] text-[#87928a] md:px-8">Version {APP_VERSION}</footer>
  </main>;
}

function Catalog({ opposites, verbs, startOpposites, startVerbs }: { opposites: number; verbs: number; startOpposites: () => void; startVerbs: (mode: VerbMode) => void }) { return <section className="mx-auto max-w-6xl px-5 py-10 md:px-8"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#3c805d]">Practice games</p><h1 className="mt-2 text-4xl font-semibold">Train what you have learned</h1><div className="mt-9 flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-[#183e2b] font-bold text-white">B1</span><div><h2 className="text-xl font-semibold">Intermediate</h2><p className="text-xs text-[#718077]">Vocabulary and verb forms</p></div></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><GameCard title="Finden Sie das Gegenteil" meta={`Vocabulary · ${opposites} exercises`} description="Enter the opposite of the highlighted word."><Button onClick={startOpposites} className="bg-[#1f6f4a] hover:bg-[#185c3d]">Play <ArrowRight /></Button></GameCard><GameCard blue title="Vergangenheitsformen der Verben" meta={`Grammar · ${verbs} verbs`} description="Transform present forms. Endings are always highlighted."><Button variant="outline" onClick={() => startVerbs('preterite')}>Präteritum</Button><Button onClick={() => startVerbs('perfect')} className="bg-[#2d3d63] hover:bg-[#243250]">Perfekt</Button></GameCard></div></section>; }
function GameCard({ title, meta, description, blue, children }: { title: string; meta: string; description: string; blue?: boolean; children: React.ReactNode }) { return <article className="overflow-hidden rounded-3xl border border-[#d8e2d8] bg-white shadow-[0_16px_45px_rgba(38,65,48,0.08)]"><div className={`${blue ? 'bg-[linear-gradient(135deg,#2d3d63,#526a9b)]' : 'bg-[linear-gradient(135deg,#193f2c,#286b49)]'} p-7 text-white`}><div className="grid size-12 place-items-center rounded-2xl bg-white/12"><Gamepad2 /></div><p className="mt-6 text-xs font-semibold uppercase tracking-[0.18em] text-white/70">{meta}</p><h3 className="mt-2 text-3xl font-semibold">{title}</h3><p className="mt-2 text-sm text-white/70">{description}</p></div><div className="flex justify-end gap-3 p-5">{children}</div></article>; }
function Feedback({ correct, children }: { correct: boolean; children: React.ReactNode }) { return <div className={`mt-5 rounded-2xl border p-4 ${correct ? 'border-[#b9dbc5] bg-[#eef8f1] text-[#1e6842]' : 'border-[#efc5bd] bg-[#fff3f0] text-[#9a3d30]'}`}><div className="flex gap-3">{correct ? <Check /> : <X />}<div><p className="font-semibold">{correct ? 'Richtig!' : 'Noch nicht.'}</p><p className="mt-1 text-sm">Correct answer: {children}</p></div></div></div>; }
