'use client';
import { useRef, useState } from 'react';
import { Download, Pencil, Plus, Trash2, Upload } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { supabase } from '@/lib/supabase';
import { hasSentenceContext, validateVerbItem, type VerbGameItem } from '@/lib/game-content';

const EMPTY = { infinitive:'', english_translation:'', present_forms:'', present_endings:'', preterite_forms:'', preterite_endings:'', perfect_auxiliary:'haben' as 'haben'|'sein', participle:'', participle_ending:'', present_sentences:'', preterite_sentences:'', perfect_sentences:'', sentence_translations:'', active:true, sort_order:10 };
const HEADER = 'infinitive\tenglish_translation\tpresent_forms\tpresent_endings\tpreterite_forms\tpreterite_endings\tperfect_auxiliary\tparticiple\tparticiple_ending\tpresent_sentences\tpreterite_sentences\tperfect_sentences\tsentence_translations\tactive\tsort_order';
const split = (value:string) => value.split('|').map(part => part.trim());
const optional = (value:string) => value.trim() ? split(value) : [];
const join = (values:string[] = []) => values.join('|');

export function VerbsPanel({ items, reload }:{ items:VerbGameItem[]; reload:()=>Promise<void> }) {
  const [open,setOpen]=useState(false); const [editingId,setEditingId]=useState<string|null>(null); const [form,setForm]=useState(EMPTY); const [message,setMessage]=useState(''); const fileRef=useRef<HTMLInputElement>(null);
  function edit(item?:VerbGameItem){setEditingId(item?.id??null);setForm(item?{infinitive:item.infinitive,english_translation:item.english_translation,present_forms:join(item.present_forms),present_endings:join(item.present_endings),preterite_forms:join(item.preterite_forms),preterite_endings:join(item.preterite_endings),perfect_auxiliary:item.perfect_auxiliary,participle:item.participle,participle_ending:item.participle_ending,present_sentences:join(item.present_sentences),preterite_sentences:join(item.preterite_sentences),perfect_sentences:join(item.perfect_sentences),sentence_translations:join(item.sentence_translations),active:item.active,sort_order:item.sort_order}:{...EMPTY,sort_order:(items.at(-1)?.sort_order??0)+10});setMessage('');setOpen(true);}
  function data(){return {level:'B1',infinitive:form.infinitive.trim(),english_translation:form.english_translation.trim(),present_forms:split(form.present_forms),present_endings:split(form.present_endings),preterite_forms:split(form.preterite_forms),preterite_endings:split(form.preterite_endings),perfect_auxiliary:form.perfect_auxiliary,participle:form.participle.trim(),participle_ending:form.participle_ending.trim(),present_sentences:optional(form.present_sentences),preterite_sentences:optional(form.preterite_sentences),perfect_sentences:optional(form.perfect_sentences),sentence_translations:optional(form.sentence_translations),active:form.active,sort_order:form.sort_order};}
  async function save(){const values=data(),problems=validateVerbItem(values);if(problems.length){setMessage(problems[0]);return;}const result=editingId?await supabase.from('verb_game_content').update(values).eq('id',editingId):await supabase.from('verb_game_content').insert(values);if(result.error){setMessage(result.error.message);return;}setOpen(false);await reload();}
  async function remove(){if(!editingId)return;const{error}=await supabase.from('verb_game_content').delete().eq('id',editingId);if(error){setMessage(error.message);return;}setOpen(false);await reload();}
  function exportTxt(){const clean=(v:string)=>v.replace(/[\t\r\n]+/g,' ');const rows=items.map(v=>[v.infinitive,v.english_translation,join(v.present_forms),join(v.present_endings),join(v.preterite_forms),join(v.preterite_endings),v.perfect_auxiliary,v.participle,v.participle_ending,join(v.present_sentences),join(v.preterite_sentences),join(v.perfect_sentences),join(v.sentence_translations),String(v.active),String(v.sort_order)].map(clean).join('\t'));const url=URL.createObjectURL(new Blob([`# Lernzeit · B1 · Vergangenheitsformen\n${HEADER}\n${rows.join('\n')}\n`],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='lernzeit-b1-vergangenheitsformen.txt';link.click();URL.revokeObjectURL(url);}
  async function importTxt(file:File){setMessage('');const lines=(await file.text()).split(/\r?\n/).filter(line=>line.trim()&&!line.startsWith('#'));if(lines[0]!==HEADER){setMessage('Invalid file. Export first to download the latest template.');return;}const rows=lines.slice(1).map((line,i)=>{const p=line.split('\t');return{level:'B1',infinitive:p[0]?.trim()??'',english_translation:p[1]?.trim()??'',present_forms:split(p[2]??''),present_endings:split(p[3]??''),preterite_forms:split(p[4]??''),preterite_endings:split(p[5]??''),perfect_auxiliary:p[6]==='sein'?'sein' as const:'haben' as const,participle:p[7]?.trim()??'',participle_ending:p[8]?.trim()??'',present_sentences:optional(p[9]??''),preterite_sentences:optional(p[10]??''),perfect_sentences:optional(p[11]??''),sentence_translations:optional(p[12]??''),active:p[13]?.trim().toLowerCase()!=='false',sort_order:Number(p[14])||(items.length+i+1)*10};});const bad=rows.findIndex(row=>validateVerbItem(row).length);if(!rows.length||bad>=0){setMessage(!rows.length?'No verb rows found.':`Import stopped on row ${bad+2}: ${validateVerbItem(rows[bad])[0]}`);return;}const{error}=await supabase.from('verb_game_content').upsert(rows,{onConflict:'infinitive'});if(error){setMessage(error.message);return;}await reload();setMessage(`Imported ${rows.length} verbs.`);}
  return <div>
    <div className="flex flex-wrap justify-end gap-2"><input ref={fileRef} type="file" accept=".txt,text/plain" className="hidden" onChange={e=>{const file=e.target.files?.[0];if(file)void importTxt(file);e.target.value='';}}/><Button variant="outline" onClick={()=>fileRef.current?.click()}><Upload/>Import .txt</Button><Button variant="outline" onClick={exportTxt}><Download/>Export .txt</Button><Button onClick={()=>edit()} className="bg-[#1f6f4a]"><Plus/>Add verb</Button></div>
    {message&&<p className="mt-4 rounded-xl bg-[#eff7f1] p-3 text-sm text-[#336848]">{message}</p>}
    <div className="mt-5 overflow-hidden rounded-2xl border bg-white">{items.map(item=><button key={item.id} onClick={()=>edit(item)} className="grid w-full grid-cols-[1fr_120px_50px] items-center gap-4 border-b px-5 py-4 text-left last:border-0 hover:bg-[#f8faf7]"><span><strong>{item.infinitive}</strong><span className="ml-2 text-xs text-[#718077]">{item.english_translation}</span><span className="mt-1 block text-xs text-[#718077]">{item.preterite_forms[0]} · {item.perfect_auxiliary} + {item.participle}</span></span><span className={`w-fit rounded-full px-2 py-1 text-xs ${hasSentenceContext(item)?'bg-[#e7eefb] text-[#315c9a]':'bg-[#eef0ee]'}`}>{hasSentenceContext(item)?'Context ready':'Forms only'}</span><Pencil size={16}/></button>)}</div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>{editingId?'Edit verb':'Add verb'}</DialogTitle><DialogDescription>Enter six values in pronoun order separated by |. All four context rows must be complete to activate Mode 2.</DialogDescription></DialogHeader><div className="grid gap-3 py-2 sm:grid-cols-2">
      <Field label="Infinitive" value={form.infinitive} setValue={v=>setForm({...form,infinitive:v})}/><Field label="English translation" value={form.english_translation} setValue={v=>setForm({...form,english_translation:v})}/>
      <label className="text-sm font-medium">Perfekt auxiliary<select className="mt-1 h-9 w-full rounded-md border bg-white px-3" value={form.perfect_auxiliary} onChange={e=>setForm({...form,perfect_auxiliary:e.target.value as 'haben'|'sein'})}><option>haben</option><option>sein</option></select></label>
      <Field wide label="Present forms" value={form.present_forms} setValue={v=>setForm({...form,present_forms:v})}/><Field wide label="Present endings" value={form.present_endings} setValue={v=>setForm({...form,present_endings:v})}/><Field wide label="Präteritum forms" value={form.preterite_forms} setValue={v=>setForm({...form,preterite_forms:v})}/><Field wide label="Präteritum endings" value={form.preterite_endings} setValue={v=>setForm({...form,preterite_endings:v})}/><Field label="Participle" value={form.participle} setValue={v=>setForm({...form,participle:v})}/><Field label="Participle ending" value={form.participle_ending} setValue={v=>setForm({...form,participle_ending:v})}/>
      <div className="mt-2 border-t pt-4 sm:col-span-2"><h3 className="font-semibold">Mode 2 · Context sentences</h3><p className="text-xs text-[#718077]">ich | du | er/sie/es | wir | ihr | sie/Sie</p></div>
      <Field wide label="Present sentences" value={form.present_sentences} setValue={v=>setForm({...form,present_sentences:v})}/><Field wide label="Präteritum sentences" value={form.preterite_sentences} setValue={v=>setForm({...form,preterite_sentences:v})}/><Field wide label="Perfekt sentences" value={form.perfect_sentences} setValue={v=>setForm({...form,perfect_sentences:v})}/><Field wide label="English sentences" value={form.sentence_translations} setValue={v=>setForm({...form,sentence_translations:v})}/>
      <Field label="Order" value={String(form.sort_order)} setValue={v=>setForm({...form,sort_order:Number(v)})}/><label className="flex items-end gap-2 pb-2 text-sm"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Visible</label>{message&&<p className="text-xs text-red-600 sm:col-span-2">{message}</p>}
    </div><DialogFooter className="justify-between sm:justify-between">{editingId?<Button variant="outline" className="text-red-600" onClick={()=>void remove()}><Trash2/>Delete</Button>:<span/>}<div className="flex gap-2"><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={()=>void save()} className="bg-[#1f6f4a]">Save</Button></div></DialogFooter></DialogContent></Dialog>
  </div>;
}
function Field({label,value,setValue,wide=false}:{label:string;value:string;setValue:(v:string)=>void;wide?:boolean}){return <label className={`text-sm font-medium ${wide?'sm:col-span-2':''}`}>{label}<Input className="mt-1" value={value} onChange={e=>setValue(e.target.value)}/></label>;}
