'use client';
import { useRef, useState } from 'react';
import { Download, Pencil, Plus, Trash2, Upload } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { supabase } from '@/lib/supabase';
import { validateVerbItem, type VerbGameItem } from '@/lib/game-content';

const EMPTY = { infinitive: '', present_forms: '', present_endings: '', preterite_forms: '', preterite_endings: '', perfect_auxiliary: 'haben' as 'haben' | 'sein', participle: '', participle_ending: '', active: true, sort_order: 10 };
export function VerbsPanel({ items, reload }: { items: VerbGameItem[]; reload: () => Promise<void> }) {
  const [open, setOpen] = useState(false); const [editingId, setEditingId] = useState<string | null>(null); const [form, setForm] = useState(EMPTY); const [message, setMessage] = useState(''); const fileRef = useRef<HTMLInputElement>(null);
  const join = (values: string[]) => values.join('|'); const split = (value: string) => value.split('|').map((part) => part.trim());
  function edit(item?: VerbGameItem) { setEditingId(item?.id ?? null); setForm(item ? { infinitive: item.infinitive, present_forms: join(item.present_forms), present_endings: join(item.present_endings), preterite_forms: join(item.preterite_forms), preterite_endings: join(item.preterite_endings), perfect_auxiliary: item.perfect_auxiliary, participle: item.participle, participle_ending: item.participle_ending, active: item.active, sort_order: item.sort_order } : { ...EMPTY, sort_order: (items.at(-1)?.sort_order ?? 0) + 10 }); setMessage(''); setOpen(true); }
  async function save() { const arrays = [split(form.present_forms), split(form.present_endings), split(form.preterite_forms), split(form.preterite_endings)]; const values = { level: 'B1', infinitive: form.infinitive.trim(), present_forms: arrays[0], present_endings: arrays[1], preterite_forms: arrays[2], preterite_endings: arrays[3], perfect_auxiliary: form.perfect_auxiliary, participle: form.participle.trim(), participle_ending: form.participle_ending.trim(), active: form.active, sort_order: form.sort_order }; const problems = validateVerbItem(values); if (problems.length) { setMessage(problems[0]); return; } const result = editingId ? await supabase.from('verb_game_content').update(values).eq('id', editingId) : await supabase.from('verb_game_content').insert(values); if (result.error) { setMessage(result.error.message); return; } setOpen(false); await reload(); }
  async function remove() { if (!editingId) return; const { error } = await supabase.from('verb_game_content').delete().eq('id', editingId); if (error) { setMessage(error.message); return; } setOpen(false); await reload(); }
  function exportTxt() { const clean = (value: string) => value.replace(/[\t\r\n]+/g, ' '); const header = 'infinitive\tpresent_forms\tpresent_endings\tpreterite_forms\tpreterite_endings\tperfect_auxiliary\tparticiple\tparticiple_ending\tactive\tsort_order'; const rows = items.map((v) => [v.infinitive, join(v.present_forms), join(v.present_endings), join(v.preterite_forms), join(v.preterite_endings), v.perfect_auxiliary, v.participle, v.participle_ending, String(v.active), String(v.sort_order)].map(clean).join('\t')); const url = URL.createObjectURL(new Blob([`# Lernzeit · B1 · Vergangenheitsformen\n${header}\n${rows.join('\n')}\n`], { type: 'text/plain;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = 'lernzeit-b1-vergangenheitsformen.txt'; a.click(); URL.revokeObjectURL(url); }
  async function importTxt(file: File) { setMessage(''); const lines = (await file.text()).split(/\r?\n/).filter((line) => line.trim() && !line.startsWith('#')); const header = 'infinitive\tpresent_forms\tpresent_endings\tpreterite_forms\tpreterite_endings\tperfect_auxiliary\tparticiple\tparticiple_ending\tactive\tsort_order'; if (lines[0] !== header) { setMessage('Invalid file. Export first to download the correct template.'); return; } const rows = lines.slice(1).map((line, i) => { const p = line.split('\t'); return { level: 'B1', infinitive: p[0]?.trim(), present_forms: split(p[1] ?? ''), present_endings: split(p[2] ?? ''), preterite_forms: split(p[3] ?? ''), preterite_endings: split(p[4] ?? ''), perfect_auxiliary: p[5] === 'sein' ? 'sein' : 'haben', participle: p[6]?.trim(), participle_ending: p[7]?.trim() ?? '', active: p[8]?.trim().toLowerCase() !== 'false', sort_order: Number(p[9]) || (items.length + i + 1) * 10 }; }); if (!rows.length) { setMessage('No verb rows found.'); return; } const invalidIndex = rows.findIndex((row) => validateVerbItem(row).length); if (invalidIndex >= 0) { setMessage(`Import stopped on row ${invalidIndex + 2}: ${validateVerbItem(rows[invalidIndex])[0]}`); return; } const { error } = await supabase.from('verb_game_content').upsert(rows, { onConflict: 'infinitive' }); if (error) { setMessage(error.message); return; } await reload(); setMessage(`Imported ${rows.length} ${rows.length === 1 ? 'verb' : 'verbs'}. Matching infinitives were updated.`); }
  return <div><div className="flex flex-wrap justify-end gap-2"><input ref={fileRef} type="file" accept=".txt,text/plain" className="hidden" onChange={(e) => { const file = e.target.files?.[0]; if (file) void importTxt(file); e.target.value = ''; }} /><Button variant="outline" onClick={() => fileRef.current?.click()}><Upload />Import .txt</Button><Button variant="outline" onClick={exportTxt}><Download />Export .txt</Button><Button onClick={() => edit()} className="bg-[#1f6f4a] hover:bg-[#185c3d]"><Plus />Add verb</Button></div>{message && <p className="mt-4 rounded-xl bg-[#eff7f1] p-3 text-sm text-[#336848]">{message}</p>}<div className="mt-5 overflow-hidden rounded-2xl border border-[#dce3d9] bg-white">{items.map((item) => <button key={item.id} onClick={() => edit(item)} className="grid w-full grid-cols-[1fr_120px_50px] items-center gap-4 border-b px-5 py-4 text-left last:border-0 hover:bg-[#f8faf7]"><span><strong>{item.infinitive}</strong><span className="mt-1 block text-xs text-[#718077]">{item.preterite_forms[0]} · {item.perfect_auxiliary} + {item.participle}</span></span><span className={`w-fit rounded-full px-2 py-1 text-xs ${item.active ? 'bg-[#e7f4eb] text-[#257049]' : 'bg-[#eef0ee]'}`}>{item.active ? 'Active' : 'Hidden'}</span><Pencil size={16} /></button>)}</div><p className="mt-3 text-xs text-[#7c8880]">Forms follow: ich | du | er/sie/es | wir | ihr | sie/Sie. Export first for the import template.</p>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{editingId ? 'Edit verb' : 'Add verb'}</DialogTitle><DialogDescription>Separate the six pronoun forms and highlighted endings with | characters.</DialogDescription></DialogHeader><div className="grid gap-3 py-2 sm:grid-cols-2"><label className="text-sm font-medium">Infinitive<Input className="mt-1" value={form.infinitive} onChange={(e) => setForm({ ...form, infinitive: e.target.value })} /></label><label className="text-sm font-medium">Perfekt auxiliary<select className="mt-1 h-9 w-full rounded-md border bg-white px-3" value={form.perfect_auxiliary} onChange={(e) => setForm({ ...form, perfect_auxiliary: e.target.value as 'haben' | 'sein' })}><option>haben</option><option>sein</option></select></label><label className="text-sm font-medium sm:col-span-2">Present forms<Input className="mt-1" value={form.present_forms} onChange={(e) => setForm({ ...form, present_forms: e.target.value })} placeholder="lerne|lernst|lernt|lernen|lernt|lernen" /></label><label className="text-sm font-medium sm:col-span-2">Present endings<Input className="mt-1" value={form.present_endings} onChange={(e) => setForm({ ...form, present_endings: e.target.value })} placeholder="e|st|t|en|t|en" /></label><label className="text-sm font-medium sm:col-span-2">Präteritum forms<Input className="mt-1" value={form.preterite_forms} onChange={(e) => setForm({ ...form, preterite_forms: e.target.value })} /></label><label className="text-sm font-medium sm:col-span-2">Präteritum endings<Input className="mt-1" value={form.preterite_endings} onChange={(e) => setForm({ ...form, preterite_endings: e.target.value })} /></label><label className="text-sm font-medium">Participle<Input className="mt-1" value={form.participle} onChange={(e) => setForm({ ...form, participle: e.target.value })} /></label><label className="text-sm font-medium">Participle ending<Input className="mt-1" value={form.participle_ending} onChange={(e) => setForm({ ...form, participle_ending: e.target.value })} placeholder="t or en" /></label><label className="text-sm font-medium">Order<Input className="mt-1" type="number" value={form.sort_order} onChange={(e) => setForm({ ...form, sort_order: Number(e.target.value) })} /></label><label className="flex items-end gap-2 pb-2 text-sm"><input type="checkbox" checked={form.active} onChange={(e) => setForm({ ...form, active: e.target.checked })} />Visible</label>{message && <p className="text-xs text-red-600 sm:col-span-2">{message}</p>}</div><DialogFooter className="justify-between sm:justify-between">{editingId ? <Button variant="outline" className="text-red-600" onClick={() => void remove()}><Trash2 />Delete</Button> : <span />}<div className="flex gap-2"><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => void save()} className="bg-[#1f6f4a]">Save</Button></div></DialogFooter></DialogContent></Dialog>
  </div>;
}
