'use client';
export const dynamic='force-static';
import { useCallback, useEffect, useMemo, useState } from 'react';
import type { User } from '@supabase/supabase-js';
import { ArrowLeft, Check, Copy, Crown, LogIn, Play, Plus, Swords, Trophy, Users, X } from 'lucide-react';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { supabase } from '@/lib/supabase';

const APP_VERSION='0.12.0', STORAGE='lernzeit-active-contest';
type Contest={id:string;join_code:string;organizer_id:string;level:string;question_count:number;visibility:'private'|'open';status:'lobby'|'active'|'finished'};
type Player={id:string;user_id:string;display_name:string;score:number;answered_count:number};
type QuestionData={game:string;title:string;prompt:string;focus:string;translation:string;answer_labels:string[]};
type Question={id:string;position:number;question:QuestionData};
type Feedback={correct:boolean;expected:string[]};
type OpenBattle={id:string;level:string;question_count:number;organizer_name:string;player_count:number;created_at:string};

export default function ContestPage(){
 const[user,setUser]=useState<User|null>(null),[contestId,setContestId]=useState<string|null>(null),[contest,setContest]=useState<Contest|null>(null),[players,setPlayers]=useState<Player[]>([]),[questions,setQuestions]=useState<Question[]>([]),[openBattles,setOpenBattles]=useState<OpenBattle[]>([]),[name,setName]=useState(''),[code,setCode]=useState(''),[level,setLevel]=useState('B1'),[count,setCount]=useState(5),[visibility,setVisibility]=useState<'private'|'open'>('private'),[answers,setAnswers]=useState<string[]>(['']),[feedback,setFeedback]=useState<Feedback|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState('');
 const me=players.find(p=>p.user_id===user?.id),current=me?questions.find(q=>q.position===me.answered_count+1):undefined,isOrganizer=contest?.organizer_id===user?.id;
 const load=useCallback(async(id:string)=>{const[c,p,q]=await Promise.all([supabase.from('contests').select('*').eq('id',id).single(),supabase.from('contest_players').select('*').eq('contest_id',id).order('score',{ascending:false}).order('answered_count',{ascending:false}),supabase.from('contest_questions').select('id,contest_id,position,question').eq('contest_id',id).order('position')]);if(c.error){setMessage(c.error.message);return;}setContest(c.data as Contest);setPlayers((p.data??[]) as Player[]);setQuestions((q.data??[]) as Question[]);},[]);
 const browse=useCallback(async()=>{const{data}=await supabase.rpc('browse_open_contests');setOpenBattles((data??[]) as OpenBattle[]);},[]);
 useEffect(()=>{void supabase.auth.getUser().then(({data})=>{setUser(data.user);if(data.user){setName(data.user.user_metadata?.full_name||data.user.email?.split('@')[0]||'Player');const saved=localStorage.getItem(STORAGE);if(saved){setContestId(saved);void load(saved);}}});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>data.subscription.unsubscribe();},[load]);
 useEffect(()=>{if(!contestId)return;const timer=window.setInterval(()=>{if(!feedback)void load(contestId);},2000);return()=>clearInterval(timer);},[contestId,feedback,load]);
 useEffect(()=>{if(!user||contestId)return;void browse();const timer=window.setInterval(()=>void browse(),3000);return()=>clearInterval(timer);},[user,contestId,browse]);
 useEffect(()=>{if(current)setAnswers(Array(current.question.answer_labels.length).fill(''));},[current?.id]);
 async function signIn(){setBusy(true);const{error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error)setMessage(error.message);}
 async function create(){setBusy(true);setMessage('');try{const rpc=visibility==='open'?'create_open_contest':'create_contest';const{data,error}=await supabase.rpc(rpc,{p_level:level,p_question_count:count,p_display_name:name});if(error)throw error;const id=(data as{id?:string}|null)?.id;if(!id)throw new Error('The contest was not created. Please try again.');localStorage.setItem(STORAGE,id);setContestId(id);await load(id);}catch(error){setMessage(error instanceof Error?error.message:'The contest could not be created.');}finally{setBusy(false);}}
 async function join(){setBusy(true);setMessage('');const{data,error}=await supabase.rpc('join_contest',{p_join_code:code.toUpperCase(),p_display_name:name});setBusy(false);if(error){setMessage(error.message);return;}const id=data as string;localStorage.setItem(STORAGE,id);setContestId(id);await load(id);}
 async function joinOpen(id:string){setBusy(true);setMessage('');const{data,error}=await supabase.rpc('join_open_contest',{p_contest_id:id,p_display_name:name});setBusy(false);if(error){setMessage(error.message);return;}const joined=data as string;localStorage.setItem(STORAGE,joined);setContestId(joined);await load(joined);}
 async function start(){if(!contest)return;setBusy(true);const{error}=await supabase.rpc('start_contest',{p_contest_id:contest.id});setBusy(false);if(error)setMessage(error.message);else await load(contest.id);}
 async function submit(){if(!contest||!current||answers.some(a=>!a.trim()))return;setBusy(true);const{data,error}=await supabase.rpc('submit_contest_answer',{p_contest_id:contest.id,p_position:current.position,p_response:answers});setBusy(false);if(error){setMessage(error.message);return;}const result=data as{correct:boolean;expected:string[]};setFeedback({correct:result.correct,expected:result.expected});}
 function next(){setFeedback(null);if(contestId)void load(contestId);}function leave(){localStorage.removeItem(STORAGE);setContestId(null);setContest(null);setPlayers([]);setQuestions([]);setFeedback(null);}
 if(!user)return <Shell><div className="mx-auto mt-16 max-w-md rounded-3xl border bg-white p-7 shadow-sm"><span className="grid size-12 place-items-center rounded-2xl bg-[#ece9fb] text-[#5b45a1]"><Swords/></span><h1 className="mt-5 text-3xl font-semibold">Join the battle</h1><p className="mt-2 text-sm text-[#718077]">Sign in so your score and identity are protected.</p><div className="mt-6 space-y-3"><Input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><Input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><Button className="w-full bg-[#5b45a1]" disabled={busy||!email||!password} onClick={()=>void signIn()}><LogIn/>Sign in</Button>{message&&<p className="text-sm text-red-600">{message}</p>}<a href="./" className="block text-center text-xs text-[#718077] underline">Create an account on the Learning Plan page</a></div></div></Shell>;
 if(!contest)return <Shell><section className="mx-auto max-w-5xl px-5 py-10"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#6b55ad]">Multiplayer</p><h1 className="mt-2 text-4xl font-semibold">German Battle</h1><p className="mt-2 text-[#718077]">Create a private room or open your lobby to every learner online.</p></div>
 <div className="mt-9 grid gap-6 md:grid-cols-2"><Card icon={<Plus/>} title="Create a contest"><Field label="Your player name"><Input maxLength={30} value={name} onChange={e=>setName(e.target.value)}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Language level"><select className="h-10 w-full rounded-md border bg-white px-3" value={level} onChange={e=>setLevel(e.target.value)}>{['A1','A2','B1','B2','C1','C2'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Questions"><select className="h-10 w-full rounded-md border bg-white px-3" value={count} onChange={e=>setCount(Number(e.target.value))}>{[5,10,15].map(v=><option key={v}>{v}</option>)}</select></Field></div><Field label="Battle visibility"><div className="grid grid-cols-2 gap-2">{(['private','open'] as const).map(value=><button type="button" key={value} onClick={()=>setVisibility(value)} className={`rounded-xl border p-3 text-left text-sm ${visibility===value?'border-[#6b55ad] bg-[#f0edfb] text-[#513d92]':'bg-white text-[#718077]'}`}><strong className="block capitalize">{value}</strong><span className="text-xs">{value==='private'?'Join code only':'Listed for everyone'}</span></button>)}</div></Field><Button disabled={busy||!name.trim()} onClick={()=>void create()} className="w-full bg-[#5b45a1]">{busy?'Creating…':'Create battle'}</Button></Card>
 <Card icon={<Users/>} title="Join a private battle"><Field label="Your player name"><Input maxLength={30} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="6-character battle code"><Input maxLength={6} className="text-center text-xl font-bold uppercase tracking-[.3em]" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></Field><Button disabled={busy||code.length!==6||!name.trim()} onClick={()=>void join()} className="w-full bg-[#173f2b]">Join private battle</Button></Card></div>
 <section className="mt-10"><div className="flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#6b55ad]">Open lobbies</p><h2 className="mt-1 text-2xl font-semibold">Battles about to start</h2></div><span className="text-xs text-[#87928a]">Updates automatically</span></div>{openBattles.length?<div className="mt-4 grid gap-3">{openBattles.map(battle=><article key={battle.id} className="flex flex-col justify-between gap-4 rounded-2xl border bg-white p-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><span className="rounded-full bg-[#ece9fb] px-2.5 py-1 text-xs font-bold text-[#5b45a1]">{battle.level}</span><strong>{battle.organizer_name}&apos;s battle</strong></div><p className="mt-2 text-sm text-[#718077]">{battle.question_count} questions · {battle.player_count}/10 players</p></div><Button disabled={busy||!name.trim()} onClick={()=>void joinOpen(battle.id)} className="bg-[#5b45a1]">Join open battle</Button></article>)}</div>:<div className="mt-4 rounded-2xl border border-dashed bg-white/60 p-8 text-center text-sm text-[#718077]">No open battles are waiting right now. Create the first one!</div>}</section>
 {message&&<p className="mx-auto mt-5 max-w-xl rounded-xl bg-red-50 p-3 text-center text-sm text-red-600">{message}</p>}</section></Shell>;
 return <Shell><section className="mx-auto max-w-6xl px-5 py-8"><button onClick={leave} className="flex items-center gap-2 text-sm text-[#718077]"><ArrowLeft size={16}/>Leave battle</button>{contest.status==='lobby'?<Lobby contest={contest} players={players} organizer={isOrganizer} busy={busy} start={start}/>:<Battle contest={contest} players={players} me={me} current={current} answers={answers} setAnswers={setAnswers} feedback={feedback} submit={submit} next={next} busy={busy}/>} {message&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-600">{message}</p>}</section></Shell>;
}
function Shell({children}:{children:React.ReactNode}){return <main className="min-h-screen bg-[#f6f5fa] text-[#17221b]"><header className="border-b bg-white px-5 py-3"><div className="mx-auto flex max-w-6xl items-center justify-between"><a href="./" className="font-semibold">Lernzeit</a><span className="flex items-center gap-2 font-semibold text-[#5b45a1]"><Swords size={18}/>German Battle</span></div></header>{children}<footer className="mx-auto max-w-6xl px-5 py-6 text-right text-[11px] text-[#87928a]">Version {APP_VERSION}</footer></main>;}
function Card({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <article className="rounded-3xl border bg-white p-6 shadow-sm"><span className="grid size-11 place-items-center rounded-xl bg-[#ece9fb] text-[#5b45a1]">{icon}</span><h2 className="mt-4 text-2xl font-semibold">{title}</h2><div className="mt-5 space-y-4">{children}</div></article>;}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-medium">{label}<div className="mt-1">{children}</div></label>;}
function Lobby({contest,players,organizer,busy,start}:{contest:Contest;players:Player[];organizer:boolean;busy:boolean;start:()=>Promise<void>}){return <div className="mx-auto mt-8 max-w-3xl text-center"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#6b55ad]">Waiting room · {contest.level} · {contest.question_count} questions</p><h1 className="mt-3 text-3xl font-semibold">Invite your opponents</h1><button onClick={()=>void navigator.clipboard.writeText(contest.join_code)} className="mx-auto mt-5 flex items-center gap-3 rounded-2xl border bg-white px-6 py-4 text-3xl font-bold tracking-[.28em] text-[#5b45a1]">{contest.join_code}<Copy size={18}/></button><p className="mt-2 text-xs text-[#718077]">Share this code · {players.length}/10 players</p><Leaderboard players={players}/>{organizer?<Button disabled={busy||!players.length} onClick={()=>void start()} className="mt-6 bg-[#5b45a1]"><Play/>Start contest</Button>:<p className="mt-6 text-sm text-[#718077]">The organizer will start the contest.</p>}</div>;}
function Battle({contest,players,me,current,answers,setAnswers,feedback,submit,next,busy}:{contest:Contest;players:Player[];me?:Player;current?:Question;answers:string[];setAnswers:(v:string[])=>void;feedback:Feedback|null;submit:()=>Promise<void>;next:()=>void;busy:boolean}){const finished=!current||contest.status==='finished';return <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_320px]"><article className="rounded-3xl border bg-white p-6 sm:p-8">{finished?<div className="py-14 text-center"><Trophy className="mx-auto text-[#d09a3a]" size={48}/><h1 className="mt-4 text-3xl font-semibold">{contest.status==='finished'?'Battle finished!':'You finished!'}</h1><p className="mt-2 text-[#718077]">Your score: {me?.score}/{contest.question_count}{contest.status!=='finished'&&' · Waiting for the others…'}</p></div>:<><div className="flex justify-between text-xs font-semibold uppercase tracking-wider text-[#6b55ad]"><span>{current.question.title}</span><span>{current.position}/{contest.question_count}</span></div><p className="mt-8 text-3xl font-medium">{current.question.prompt}</p><p className="mt-3 text-sm font-medium text-[#5b45a1]">{current.question.focus}</p><p className="mt-2 text-sm text-[#718077]">{current.question.translation}</p><div className="mt-8 space-y-3">{current.question.answer_labels.map((label,i)=><Field key={label} label={label}><Input disabled={!!feedback} value={answers[i]??''} onChange={e=>{const next=[...answers];next[i]=e.target.value;setAnswers(next);}}/></Field>)}{feedback?<div className={`rounded-xl p-4 ${feedback.correct?'bg-green-50 text-green-700':'bg-red-50 text-red-700'}`}><p className="flex items-center gap-2 font-semibold">{feedback.correct?<Check/>:<X/>}{feedback.correct?'Richtig!':'Noch nicht.'}</p>{!feedback.correct&&feedback.expected.map((a,i)=><p key={a} className="mt-1 text-sm">{current.question.answer_labels[i]}: {a}</p>)}<Button onClick={next} className="mt-3">Next</Button></div>:<Button disabled={busy||answers.some(a=>!a.trim())} onClick={()=>void submit()} className="w-full bg-[#5b45a1]">Submit answer</Button>}</div></>}</article><Leaderboard players={players}/></div>;}
function Leaderboard({players}:{players:Player[]}){const ordered=useMemo(()=>[...players].sort((a,b)=>b.score-a.score||b.answered_count-a.answered_count),[players]);return <aside className="mt-6 rounded-3xl border bg-white p-5 text-left"><h2 className="flex items-center gap-2 font-semibold"><Crown size={18} className="text-[#d09a3a]"/>Leaderboard</h2><div className="mt-4 space-y-2">{ordered.map((p,i)=><div key={p.id} className="flex items-center justify-between rounded-xl bg-[#f7f6fb] px-3 py-2"><span><strong className="mr-2 text-[#6b55ad]">#{i+1}</strong>{p.display_name}</span><span className="font-semibold">{p.score} <span className="text-xs font-normal text-[#87928a]">· {p.answered_count} played</span></span></div>)}</div></aside>;}
