'use client';
export const dynamic='force-static';
import { useCallback, useEffect, useMemo, useState } from 'react';
import type { User } from '@supabase/supabase-js';
import { ArrowLeft, CalendarDays, Check, Clock3, Copy, Crown, LogIn, Play, Plus, Settings, Swords, Trophy, Users, X } from 'lucide-react';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { supabase } from '@/lib/supabase';

const APP_VERSION='0.19.0', STORAGE='lernzeit-active-contest';
type Contest={id:string;join_code:string;organizer_id:string;level:string;question_count:number;response_time_seconds:number;scheduled_for:string;started_at:string|null;visibility:'private'|'open';status:'lobby'|'active'|'finished'};
type Player={id:string;user_id:string;display_name:string;score:number;answered_count:number;question_started_at:string|null};
type QuestionData={game:string;title:string;prompt:string;focus:string;translation:string;answer_labels:string[]};
type Question={id:string;position:number;question:QuestionData};
type Feedback={correct:boolean;expected:string[];timed_out?:boolean};
type OpenBattle={id:string;level:string;question_count:number;response_time_seconds:number;scheduled_for:string;organizer_name:string;player_count:number;created_at:string;is_organizer:boolean};
function dateInput(days=0){const date=new Date();date.setDate(date.getDate()+days);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
function scheduledLabel(value:string){return new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Vienna'}).format(new Date(value));}

export default function ContestPage(){
 const[user,setUser]=useState<User|null>(null),[contestId,setContestId]=useState<string|null>(null),[contest,setContest]=useState<Contest|null>(null),[players,setPlayers]=useState<Player[]>([]),[questions,setQuestions]=useState<Question[]>([]),[openBattles,setOpenBattles]=useState<OpenBattle[]>([]),[name,setName]=useState(''),[code,setCode]=useState(''),[level,setLevel]=useState('B1'),[count,setCount]=useState(5),[responseTime,setResponseTime]=useState(60),[battleDate,setBattleDate]=useState(()=>dateInput(1)),[battleTime,setBattleTime]=useState('18:00'),[visibility,setVisibility]=useState<'private'|'open'>('private'),[answers,setAnswers]=useState<string[]>(['']),[feedback,setFeedback]=useState<Feedback|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authMode,setAuthMode]=useState<'signin'|'signup'>('signin');
 const me=players.find(p=>p.user_id===user?.id),current=me?questions.find(q=>q.position===me.answered_count+1):undefined,isOrganizer=contest?.organizer_id===user?.id;
 const load=useCallback(async(id:string)=>{const[c,p,q]=await Promise.all([supabase.from('contests').select('*').eq('id',id).single(),supabase.from('contest_players').select('*').eq('contest_id',id).order('score',{ascending:false}).order('answered_count',{ascending:false}),supabase.from('contest_questions').select('id,contest_id,position,question').eq('contest_id',id).order('position')]);if(c.error){setMessage(c.error.message);return;}setContest(c.data as Contest);setPlayers((p.data??[]) as Player[]);setQuestions((q.data??[]) as Question[]);},[]);
 const browse=useCallback(async()=>{const{data}=await supabase.rpc('browse_open_contests');setOpenBattles((data??[]) as OpenBattle[]);},[]);
 useEffect(()=>{void supabase.auth.getUser().then(({data})=>{setUser(data.user);if(data.user){setName(data.user.user_metadata?.full_name||data.user.email?.split('@')[0]||'Player');const saved=localStorage.getItem(STORAGE);if(saved){setContestId(saved);void load(saved);}}});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>data.subscription.unsubscribe();},[load]);
 useEffect(()=>{if(!contestId)return;const timer=window.setInterval(()=>{if(!feedback)void load(contestId);},2000);return()=>clearInterval(timer);},[contestId,feedback,load]);
 useEffect(()=>{if(!user||contestId)return;void browse();const timer=window.setInterval(()=>void browse(),3000);return()=>clearInterval(timer);},[user,contestId,browse]);
 useEffect(()=>{if(current)setAnswers(Array(current.question.answer_labels.length).fill(''));},[current?.id]);
 async function submitAuth(){setBusy(true);setMessage('');const result=authMode==='signup'?await supabase.auth.signUp({email,password,options:{emailRedirectTo:'https://spirea89.github.io/GermanLearning/'}}):await supabase.auth.signInWithPassword({email,password});setBusy(false);if(result.error)setMessage(result.error.message);else if(authMode==='signup'&&!result.data.session)setMessage('Account created. Check your email to confirm your address, then sign in.');}
 async function create(){setBusy(true);setMessage('');try{const scheduledFor=new Date(`${battleDate}T${battleTime}:00`).toISOString();const rpc=visibility==='open'?'create_open_contest':'create_contest';const{data,error}=await supabase.rpc(rpc,{p_level:level,p_question_count:count,p_display_name:name,p_response_time_seconds:responseTime,p_scheduled_for:scheduledFor});if(error)throw error;const id=(data as{id?:string}|null)?.id;if(!id)throw new Error('The contest was not created. Please try again.');localStorage.setItem(STORAGE,id);setContestId(id);await load(id);}catch(error){setMessage(error instanceof Error?error.message:'The contest could not be created.');}finally{setBusy(false);}}
 async function join(){setBusy(true);setMessage('');const{data,error}=await supabase.rpc('join_contest',{p_join_code:code.toUpperCase(),p_display_name:name});setBusy(false);if(error){setMessage(error.message);return;}const id=data as string;localStorage.setItem(STORAGE,id);setContestId(id);await load(id);}
 async function joinOpen(id:string){setBusy(true);setMessage('');const{data,error}=await supabase.rpc('join_open_contest',{p_contest_id:id,p_display_name:name});setBusy(false);if(error){setMessage(error.message);return;}const joined=data as string;localStorage.setItem(STORAGE,joined);setContestId(joined);await load(joined);}
 async function manageOpen(id:string){setBusy(true);setMessage('');localStorage.setItem(STORAGE,id);setContestId(id);await load(id);setBusy(false);}
 async function start(){if(!contest)return;setBusy(true);const{error}=await supabase.rpc('start_contest',{p_contest_id:contest.id});setBusy(false);if(error)setMessage(error.message);else await load(contest.id);}
 async function submit(timedOut=false){if(!contest||!current||(!timedOut&&answers.some(a=>!a.trim())))return;setBusy(true);const response=timedOut?Array(current.question.answer_labels.length).fill(''):answers;const{data,error}=await supabase.rpc('submit_contest_answer',{p_contest_id:contest.id,p_position:current.position,p_response:response});if(error){setBusy(false);setMessage(error.message);return;}if(timedOut){setFeedback(null);await load(contest.id);setBusy(false);return;}setBusy(false);const result=data as Feedback;setFeedback(result);}
 function next(){setFeedback(null);if(contestId)void load(contestId);}function leave(){localStorage.removeItem(STORAGE);setContestId(null);setContest(null);setPlayers([]);setQuestions([]);setFeedback(null);}
 if(!user)return <Shell><div className="mx-auto mt-8 max-w-md rounded-3xl border bg-white p-5 shadow-sm sm:mt-16 sm:p-7"><span className="grid size-12 place-items-center rounded-2xl bg-[#ece9fb] text-[#5b45a1]"><Swords/></span><h1 className="mt-5 text-3xl font-semibold">{authMode==='signup'?'Create your account':'Join the battle'}</h1><p className="mt-2 text-sm text-[#718077]">{authMode==='signup'?'Create an account to join battles and save your progress.':'Sign in so your score and identity are protected.'}</p><form onSubmit={e=>{e.preventDefault();void submitAuth();}} className="mt-6 space-y-3"><Input type="email" aria-label="Email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/><Input type="password" aria-label="Password" placeholder="Password (6 characters minimum)" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={authMode==='signup'?'new-password':'current-password'}/><Button type="submit" className="w-full bg-[#5b45a1]" disabled={busy||!email||password.length<6}><LogIn/>{busy?'Please wait…':authMode==='signup'?'Create account':'Sign in'}</Button>{message&&<p role="status" className="text-sm text-red-600">{message}</p>}<button type="button" onClick={()=>{setAuthMode(authMode==='signup'?'signin':'signup');setMessage('');}} className="block w-full py-2 text-center text-sm font-medium underline underline-offset-4">{authMode==='signup'?'Already have an account? Sign in':'New here? Create an account'}</button></form></div></Shell>;
 if(!contest)return <Shell><section className="mx-auto max-w-5xl px-5 py-10"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#6b55ad]">Multiplayer</p><h1 className="mt-2 text-4xl font-semibold">German Battle</h1><p className="mt-2 text-[#718077]">Create a private room or open your lobby to every learner online.</p></div>
 <div className="mt-9 grid gap-6 md:grid-cols-2"><Card icon={<Plus/>} title="Create a contest"><Field label="Your player name"><Input maxLength={30} value={name} onChange={e=>setName(e.target.value)}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Language level"><select className="h-10 w-full rounded-md border bg-white px-3" value={level} onChange={e=>setLevel(e.target.value)}>{['A1','A2','B1','B2','C1','C2'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Questions"><select className="h-10 w-full rounded-md border bg-white px-3" value={count} onChange={e=>setCount(Number(e.target.value))}>{[5,10,15].map(v=><option key={v}>{v}</option>)}</select></Field></div><div className="grid grid-cols-2 gap-3"><Field label="Battle day"><Input type="date" min={dateInput()} value={battleDate} onChange={e=>setBattleDate(e.target.value)}/></Field><Field label="Start time"><Input type="time" value={battleTime} onChange={e=>setBattleTime(e.target.value)}/></Field></div><Field label="Time per question"><select className="h-10 w-full rounded-md border bg-white px-3" value={responseTime} onChange={e=>setResponseTime(Number(e.target.value))}>{Array.from({length:12},(_,i)=>(i+1)*10).map(v=><option key={v} value={v}>{v} seconds{v===60?' · Default':''}</option>)}</select></Field><Field label="Battle visibility"><div className="grid grid-cols-2 gap-2">{(['private','open'] as const).map(value=><button type="button" key={value} aria-pressed={visibility===value} onClick={()=>setVisibility(value)} className={`battle-visibility-option rounded-xl border p-3 text-left text-sm ${visibility===value?'is-selected':''}`}><strong className="block capitalize">{value}</strong><span className="text-xs">{value==='private'?'Join code only':'Listed for everyone'}</span></button>)}</div></Field><Button disabled={busy||!name.trim()||!battleDate||!battleTime} onClick={()=>void create()} className="w-full bg-[#5b45a1]">{busy?'Creating…':'Create battle'}</Button></Card>
 <Card icon={<Users/>} title="Join a private battle"><Field label="Your player name"><Input maxLength={30} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="6-character battle code"><Input maxLength={6} className="text-center text-xl font-bold uppercase tracking-[.3em]" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></Field><Button disabled={busy||code.length!==6||!name.trim()} onClick={()=>void join()} className="w-full bg-[#173f2b]">Join private battle</Button></Card></div>
 <section className="mt-10"><div className="flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#6b55ad]">Open lobbies</p><h2 className="mt-1 text-2xl font-semibold">Scheduled battles</h2></div><span className="text-xs text-[#87928a]">Updates automatically</span></div>{openBattles.length?<div className="mt-4 grid gap-3">{openBattles.map(battle=><article key={battle.id} className="flex flex-col justify-between gap-4 rounded-2xl border bg-white p-4 sm:flex-row sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#ece9fb] px-2.5 py-1 text-xs font-bold text-[#5b45a1]">{battle.level}</span><strong>{battle.organizer_name}&apos;s battle</strong>{battle.is_organizer&&<span className="rounded-full bg-[#e7f4eb] px-2.5 py-1 text-xs font-semibold text-[#257049]">Your battle</span>}</div><p className="mt-2 flex flex-wrap items-center gap-x-2 text-sm text-[#718077]"><span className="inline-flex items-center gap-1 font-semibold"><CalendarDays size={14}/>{scheduledLabel(battle.scheduled_for)}</span><span>· {battle.question_count} questions · {battle.response_time_seconds}s each · {battle.player_count}/10 players</span></p></div>{battle.is_organizer?<Button disabled={busy} onClick={()=>void manageOpen(battle.id)} className="bg-[#173f2b]"><Settings/>Manage battle</Button>:<Button disabled={busy||!name.trim()} onClick={()=>void joinOpen(battle.id)} className="bg-[#5b45a1]">Join &amp; add to calendar</Button>}</article>)}</div>:<div className="mt-4 rounded-2xl border border-dashed bg-white/60 p-8 text-center text-sm text-[#718077]">No open battles are scheduled right now. Create the first one!</div>}</section>
 {message&&<p className="mx-auto mt-5 max-w-xl rounded-xl bg-red-50 p-3 text-center text-sm text-red-600">{message}</p>}</section></Shell>;
 return <Shell><section className="mx-auto max-w-6xl px-5 py-8"><button onClick={leave} className="flex items-center gap-2 text-sm text-[#718077]"><ArrowLeft size={16}/>Leave battle</button>{contest.status==='lobby'?<Lobby contest={contest} players={players} organizer={isOrganizer} busy={busy} start={start}/>:<Battle contest={contest} players={players} me={me} current={current} answers={answers} setAnswers={setAnswers} feedback={feedback} submit={submit} next={next} busy={busy}/>} {message&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-600">{message}</p>}</section></Shell>;
}
function Shell({children}:{children:React.ReactNode}){return <main className="min-h-screen bg-[#f6f5fa] text-[#17221b]"><header className="border-b bg-white px-5 py-3"><div className="mx-auto flex max-w-6xl items-center justify-between"><a href="./" className="font-semibold">Lernzeit</a><span className="flex items-center gap-2 font-semibold text-[#5b45a1]"><Swords size={18}/>German Battle</span></div></header>{children}<footer className="mx-auto max-w-6xl px-5 py-6 text-right text-[11px] text-[#87928a]">Version {APP_VERSION}</footer></main>;}
function Card({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <article className="rounded-3xl border bg-white p-6 shadow-sm"><span className="grid size-11 place-items-center rounded-xl bg-[#ece9fb] text-[#5b45a1]">{icon}</span><h2 className="mt-4 text-2xl font-semibold">{title}</h2><div className="mt-5 space-y-4">{children}</div></article>;}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-medium">{label}<div className="mt-1">{children}</div></label>;}
function Lobby({contest,players,organizer,busy,start}:{contest:Contest;players:Player[];organizer:boolean;busy:boolean;start:()=>Promise<void>}){const[now,setNow]=useState(Date.now());useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer);},[]);const ready=now>=new Date(contest.scheduled_for).getTime();return <div className="mx-auto mt-8 max-w-3xl text-center"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#6b55ad]">Waiting room · {contest.level} · {contest.question_count} questions · {contest.response_time_seconds}s each</p><h1 className="mt-3 text-3xl font-semibold">Invite your opponents</h1><p className="mx-auto mt-4 inline-flex items-center gap-2 rounded-full bg-[#ece9fb] px-4 py-2 text-sm font-semibold text-[#5b45a1]"><CalendarDays size={16}/>{scheduledLabel(contest.scheduled_for)}</p><button onClick={()=>void navigator.clipboard.writeText(contest.join_code)} className="mx-auto mt-5 flex items-center gap-3 rounded-2xl border bg-white px-6 py-4 text-3xl font-bold tracking-[.28em] text-[#5b45a1]">{contest.join_code}<Copy size={18}/></button><p className="mt-2 text-xs text-[#718077]">Share this code · {players.length}/10 players · Added to every player&apos;s Learning Plan</p><Leaderboard players={players}/>{organizer?<><Button disabled={busy||!players.length||!ready} onClick={()=>void start()} className="mt-6 bg-[#5b45a1]"><Play/>{ready?'Start contest':'Waiting for scheduled time'}</Button>{!ready&&<p className="mt-2 text-xs text-[#718077]">The start button unlocks at the scheduled time.</p>}</>:<p className="mt-6 text-sm text-[#718077]">The organizer can start the contest at the scheduled time.</p>}</div>;}
function Battle({contest,players,me,current,answers,setAnswers,feedback,submit,next,busy}:{contest:Contest;players:Player[];me?:Player;current?:Question;answers:string[];setAnswers:(v:string[])=>void;feedback:Feedback|null;submit:(timedOut?:boolean)=>Promise<void>;next:()=>void;busy:boolean}){
 const[remaining,setRemaining]=useState(contest.response_time_seconds);
 useEffect(()=>{
  if(!current||!me?.question_started_at||feedback)return;
  const deadline=new Date(me.question_started_at).getTime()+contest.response_time_seconds*1000;
  const update=()=>setRemaining(Math.max(0,Math.ceil((deadline-Date.now())/1000)));
  update();const timer=window.setInterval(update,250);return()=>window.clearInterval(timer);
 },[current?.id,me?.question_started_at,contest.response_time_seconds,feedback]);
 useEffect(()=>{if(current&&remaining===0&&!feedback&&!busy)void submit(true);},[remaining,current?.id,feedback,busy,submit]);
 const finished=!current||contest.status==='finished',urgent=remaining<=10;
 return <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_320px]"><article className="rounded-3xl border bg-white p-6 sm:p-8">{finished?<div className="py-14 text-center"><Trophy className="mx-auto text-[#d09a3a]" size={48}/><h1 className="mt-4 text-3xl font-semibold">{contest.status==='finished'?'Battle finished!':'You finished!'}</h1><p className="mt-2 text-[#718077]">Your score: {me?.score}/{contest.question_count}{contest.status!=='finished'&&' · Waiting for the others…'}</p></div>:<><div className="flex items-center justify-between gap-3 text-xs font-semibold uppercase tracking-wider text-[#6b55ad]"><span>{current.question.title}</span><span className="flex items-center gap-3"><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-sm font-bold normal-case tracking-normal ${urgent?'bg-red-50 text-red-700':'bg-[#ece9fb] text-[#5b45a1]'}`}><Clock3 size={15}/>{remaining}s</span><span>{current.position}/{contest.question_count}</span></span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-[#ece9fb]"><div className={`h-full rounded-full transition-[width] ${urgent?'bg-red-500':'bg-[#6b55ad]'}`} style={{width:`${remaining/contest.response_time_seconds*100}%`}}/></div><p className="mt-8 text-3xl font-medium">{current.question.prompt}</p><p className="mt-3 text-sm font-medium text-[#5b45a1]">{current.question.focus}</p><p className="mt-2 text-sm text-[#718077]">{current.question.translation}</p><div className="mt-8 space-y-3">{current.question.answer_labels.map((label,i)=><Field key={label} label={label}><Input disabled={!!feedback||busy} value={answers[i]??''} onChange={e=>{const next=[...answers];next[i]=e.target.value;setAnswers(next);}}/></Field>)}{feedback?<div className={`rounded-xl p-4 ${feedback.correct?'bg-green-50 text-green-700':'bg-red-50 text-red-700'}`}><p className="flex items-center gap-2 font-semibold">{feedback.correct?<Check/>:<X/>}{feedback.correct?'Richtig!':feedback.timed_out?'Time is up!':'Noch nicht.'}</p>{!feedback.correct&&feedback.expected.map((a,i)=><p key={a} className="mt-1 text-sm">{current.question.answer_labels[i]}: {a}</p>)}<Button onClick={next} className="mt-3">Next</Button></div>:<Button disabled={busy||answers.some(a=>!a.trim())} onClick={()=>void submit()} className="w-full bg-[#5b45a1]">Submit answer</Button>}</div></>}</article><Leaderboard players={players}/></div>;
}
function Leaderboard({players}:{players:Player[]}){const ordered=useMemo(()=>[...players].sort((a,b)=>b.score-a.score||b.answered_count-a.answered_count),[players]);return <aside className="mt-6 rounded-3xl border bg-white p-5 text-left"><h2 className="flex items-center gap-2 font-semibold"><Crown size={18} className="text-[#d09a3a]"/>Leaderboard</h2><div className="mt-4 space-y-2">{ordered.map((p,i)=><div key={p.id} className="flex items-center justify-between rounded-xl bg-[#f7f6fb] px-3 py-2"><span><strong className="mr-2 text-[#6b55ad]">#{i+1}</strong>{p.display_name}</span><span className="font-semibold">{p.score} <span className="text-xs font-normal text-[#87928a]">· {p.answered_count} played</span></span></div>)}</div></aside>;}
